@extends('layouts.app')

@section('content')
<div class="relative min-h-screen pt-20 flex items-center justify-center overflow-hidden">
    <div class="absolute inset-0 bg-cover bg-center bg-no-repeat" style="
        /* The image URL is generated by the Blade asset helper */
        background-image: url('{{ asset('images/20.png') }}');
        /* Added dark overlay for text contrast and z-index to stay behind everything */
        background-blend-mode: multiply;
        background-color: rgba(0, 0, 0, 0.5);
        z-index: 1; /* Set z-index low (e.g., 1) to be behind content/logos */
    "></div>

    <div class="max-w-4xl mx-auto text-center p-6 sm:p-10 relative z-10">
        
        <h1 class="text-5xl sm:text-7xl font-extrabold text-white leading-tight tracking-tight mb-4 uppercase">
            STAY AHEAD
            <span class="block text-4xl sm:text-6xl mt-2">IN SHIPPING AND LOGISTICS</span>
        </h1>

        <p class="text-lg text-gray-300 mb-10 max-w-lg mx-auto">
            Discover key insights and trends to enhance your shipping strategies and stay competitive.
        </p>

        <div class="flex flex-col sm:flex-row justify-center space-y-4 sm:space-y-0 sm:space-x-6 mb-16">
           <a href="#" >
    <img src="{{ asset('images/Contactus.png') }}" 
         alt="Contact Us Button" 
         class="h-10 w-auto">
</a>
  <a href="#" class="inline-block">
    <img src="{{ asset('images/play.png') }}" 
         alt="Play Button" 
         class="h-10 w-auto rounded">
</a>

        </div>

        <div class="absolute inset-0 flex items-center justify-center pointer-events-none">
            
            <div class="absolute top-[50%] right-4 sm:top-[50%] sm:right-6">
    <img src="{{ asset('images/Adidas.png') }}" 
         alt="Tata Logo" 
         class="w-16 h-8 sm:w-20 sm:h-10 rounded-full p-1  shadow-xl opacity-90">
</div>

            <div class="absolute top-0 right-[10%] sm:top-0 sm:right-[10%]">
    <img src="{{ asset('images/myntra.png') }}" 
         alt="Myntra Logo" 
         class="w-16 h-8 sm:w-20 sm:h-10 rounded-full p-1  shadow-xl opacity-90">
</div>

            
            <div class="absolute bottom-[30%] left-[25%] sm:bottom-[35%] sm:left-[22%]">
                <img src="{{ asset('images/lego.png') }}" alt="Lego Logo" class="w-16 h-8 sm:w-20 sm:h-10 rounded-full p-1  shadow-xl opacity-90">
            </div>

            <div class="absolute top-[50%] left-[30%] sm:top-[10%] sm:left-[10%]">
                <img src="{{ asset('images/hero.png') }}" alt="Hero Logo" class="w-16 h-8 sm:w-20 sm:h-10 rounded-full p-1  shadow-xl opacity-90">
            </div>

        <div class="absolute top-[45%] left-0 sm:top-[50%] sm:left-0">
    <img src="{{ asset('images/tata.png') }}" 
         alt="Adidas Logo" 
         class="w-16 h-8 sm:w-20 sm:h-10 rounded-full p-1  shadow-xl opacity-90">
</div>



           <div class="absolute top-[35%] right-0 sm:top-[30%] sm:right-0">
    <img src="{{ asset('images/h&m.png') }}" 
         alt="H&M Logo" 
         class="w-16 h-8 sm:w-20 sm:h-10 rounded-full p-1  shadow-xl opacity-90">
</div>

        </div>
        
    </div>
</div>

<section class="py-24 sm:py-32 bg-white text-gray-900">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        
        <p class="text-sm font-semibold tracking-wider uppercase text-gray-500 mb-2">Explore</p>
        <h2 class="text-4xl sm:text-5xl font-extrabold tracking-tight mb-4 text-gray-900">
            Built For Global Shipping
        </h2>
        <p class="text-lg text-gray-600 mb-10 max-w-2xl mx-auto">
            Ship X delivers smart and efficient logistics solutions to simplify global shipping for businesses
        </p>

        <div class="flex justify-center space-x-4 mb-20">
            <a href="#" class="
                bg-indigo-600 hover:bg-indigo-700 text-white font-semibold 
                py-3 px-8 rounded-full shadow-lg 
                transition duration-300 flex items-center justify-center
            ">
                Contact us
            </a>
            
            <a href="#" class="
                bg-white border border-gray-300 text-gray-900 font-semibold 
                py-3 px-8 rounded-full shadow-md hover:shadow-lg 
                transition duration-300 flex items-center justify-center space-x-2
            ">
                <span>Get Started</span>
                <svg class="w-4 h-4 text-gray-900" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path>
                </svg>
            </a>
        </div>

       <div class="relative flex justify-center items-center h-full">
    <div class="flex overflow-hidden justify-center items-end space-x-2 sm:space-x-4">
        <div class="hidden md:block w-[150px] sm:w-[180px] lg:w-[200px]">
            <img src="{{ asset('images/5.png') }}" alt="App Screenshot 1" class="rounded-3xl shadow-2xl w-full h-auto">
        </div>

        <div class="w-[150px] sm:w-[180px] lg:w-[200px]">
            <img src="{{ asset('images/4.png') }}" alt="App Screenshot 2" class="rounded-3xl shadow-2xl w-full h-auto">
        </div>
        
        <div class="z-10 w-[170px] sm:w-[200px] lg:w-[250px]">
            <img src="{{ asset('images/1.png') }}" alt="App Screenshot 3 - Focus" class="rounded-3xl shadow-2xl w-full h-auto">
        </div>

        <div class="w-[150px] sm:w-[180px] lg:w-[200px]">
            <img src="{{ asset('images/2.png') }}" alt="App Screenshot 4" class="rounded-3xl shadow-2xl w-full h-auto">
        </div>

        <div class="hidden md:block w-[150px] sm:w-[180px] lg:w-[200px]">
            <img src="{{ asset('images/3.png') }}" alt="App Screenshot 5" class="rounded-3xl shadow-2xl w-full h-auto">
        </div>

    </div>
</div>

    </div>
</section>
 <!-- Start of the feature section -->
    <section class="py-24 sm:py-32 bg-dark-purple text-white overflow-hidden w-full">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            
            <!-- Main Grid: 1 column on mobile, 2 columns on large screens -->
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
                
                <!-- LEFT COLUMN: Text, Buttons, and Featured Image Card -->
                <div class="lg:pr-12">
                    
                    <p class="text-sm font-semibold tracking-wider uppercase text-gray-400 mb-2">How we work</p>
                    <h2 class="text-5xl sm:text-6xl font-extrabold tracking-tight mb-6 text-white leading-tight">
                        Our Genius 
                        <span class="block">Shipping Flow</span>
                    </h2>
                    <p class="text-lg text-gray-300 mb-12 max-w-md">
                        We make shipping simple with fast booking, real-time tracking, and secure, on-time delivery for every cargo across the globe.
                    </p>
                    
                    <!-- Action Buttons -->
                    <div class="flex space-x-4 mb-16">
                        <!-- Note: Using Tailwind variables instead of explicit hex codes for consistency -->
                        <a href="#" class="bg-light-blue hover:bg-[#4a54c9] text-white font-semibold py-3 px-8 rounded-full shadow-lg transition duration-300 flex items-center justify-center space-x-2">
                            <span>Contact us</span>
                            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"></path></svg>
                        </a>
                        <a href="#" class="bg-medium-purple hover:bg-[#323049] text-white font-semibold py-3 px-8 rounded-full shadow-md transition duration-300 flex items-center justify-center space-x-2 border border-transparent">
                            <span>Get Started</span>
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path></svg>
                        </a>
                    </div>
                    
                    <!-- Featured Image Card -->
                    <div class="relative rounded-2xl shadow-2xl overflow-hidden max-w-md w-full">
                        <!-- Using the uploaded ship image -->
                        <img 
                            src="ship_flow_image.jpg" 
                            alt="A large sailing ship navigating open water, illustrating robust tracking." 
                            class="w-full h-auto object-cover opacity-90 rounded-2xl aspect-[4/3] sm:aspect-video"
                            onerror="this.onerror=null;this.src='https://placehold.co/600x400/1e293b/ffffff?text=Shipping+Image+Placeholder';"
                        >
                        
                        <!-- Overlay Text and Gradient -->
                        <div class="absolute bottom-0 left-0 p-6 bg-gradient-to-t from-black/80 to-transparent w-full">
                            <h4 class="text-white font-bold text-xl mb-2">Track shipments, view reports, and monitor analytics</h4>
                            <p class="text-gray-300 text-sm max-w-xs">
                                — all in one <strong class="text-indigo-400">smart dashboard</strong> built for fast, clear, and efficient shipping flow.
                            </p>
                        </div>
                        <div class="absolute inset-0 rounded-2xl ring-4 ring-indigo-500/50 pointer-events-none"></div>
                    </div>

                </div>

                <!-- RIGHT COLUMN: Image replacements for Dashboard Cards -->
                <div class="lg:pt-0">
                    <div class="right-column-grid grid gap-6 h-full">
                        
                        <!-- Image 1: Placeholder for Custom Reports -->
                        <!-- Using card.png as requested, stretching across 2 columns on mobile/small screens for a better look -->
                        <div class="col-span-1 md:col-span-2">
                            <div class="bg-medium-purple rounded-2xl shadow-2xl h-full flex flex-col border border-dark-border p-0 overflow-hidden">
                                <img 
                                    src="card.png" 
                                    alt="Dashboard Mockup showing custom reports" 
                                    class="dashboard-image"
                                    onerror="this.onerror=null;this.src='https://placehold.co/600x400/26243A/9CA3AF?text=Report+Image+Placeholder';"
                                >
                            </div>
                        </div>

                        <!-- Image 2: Placeholder for Shipment Statistics (Top-Right on large screens, now second image) -->
                        <div class="col-span-1 md:col-span-1">
                            <div class="bg-medium-purple rounded-2xl shadow-2xl h-full flex flex-col border border-dark-border p-0 overflow-hidden">
                                <img 
                                    src="Statistics.png" 
                                    alt="Dashboard Mockup showing shipment statistics chart" 
                                    class="dashboard-image"
                                    onerror="this.onerror=null;this.src='https://placehold.co/300x300/26243A/9CA3AF?text=Stats+Image+Placeholder';"
                                >
                            </div>
                        </div>

                        <!-- Image 3: Placeholder for Analytical View (Bottom-Right on large screens, now third image) -->
                        <!-- Using the third uploaded image to fill the remaining spot -->
                        <div class="col-span-1 md:col-span-1">
                            <div class="bg-medium-purple rounded-2xl shadow-2xl h-full flex flex-col border border-dark-border p-0 overflow-hidden">
                                <img 
                                    src="image_2ecc9a.png" 
                                    alt="Dashboard Mockup showing analytical gauge view" 
                                    class="dashboard-image"
                                    onerror="this.onerror=null;this.src='https://placehold.co/300x300/26243A/9CA3AF?text=Analytics+Image+Placeholder';"
                                >
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<section class="relative py-24 sm:py-32 bg-white text-gray-900 overflow-hidden">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            
            <div class="relative flex items-center justify-center p-6 lg:p-0">
                
                <div class="relative w-full max-w-lg h-[400px] sm:h-[450px] lg:h-[500px]">
                    
                    <div class="absolute inset-0 rounded-2xl shadow-xl overflow-hidden bg-gray-100">
                         <img src="{{ asset('images/Card1.png') }}" alt="Delivery person handing over a package" class="w-full h-full object-cover">
                    </div>
                    
                    

                </div>
            </div>

            <div class="lg:pl-12 text-center lg:text-left">
                <p class="text-sm font-semibold tracking-wider uppercase text-gray-500 mb-2">Explore</p>
                <h2 class="text-4xl sm:text-5xl font-extrabold tracking-tight mb-6 text-gray-900 leading-tight">
                    Our Industry 
                    <span class="block">Leading Shipping</span>
                    <span class="block">Solutions</span>
                </h2>
                <p class="text-lg text-gray-600 mb-12 max-w-lg mx-auto lg:mx-0">
                    Ship X delivers smart and efficient logistics solutions, combining technology and expertise to simplify global shipping for businesses.
                </p>

                <div class="flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4 justify-center lg:justify-start">
                    <a href="#" class="
                        bg-indigo-600 hover:bg-indigo-700 text-white font-semibold 
                        py-3 px-8 rounded-full shadow-lg 
                        transition duration-300 flex items-center justify-center space-x-2
                    ">
                        <span>Contact us</span>
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"></path>
                        </svg>
                    </a>
                    
                    <a href="#" class="
                        bg-gray-100 hover:bg-gray-200 text-gray-800 font-semibold 
                        py-3 px-8 rounded-full shadow-md 
                        transition duration-300 flex items-center justify-center space-x-2
                    ">
                        <span>Get Started</span>
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path>
                        </svg>
                    </a>
                </div>
            </div>
            
        </div>
    </div>
</section>
<section class="bg-white py-16 md:py-24">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col lg:flex-row items-center gap-12">

        <div class="lg:w-1/2 w-full space-y-6 text-center lg:text-left">
            
            <p class="text-sm font-semibold text-gray-500 uppercase tracking-widest bg-gray-100 inline-block px-3 py-1 rounded-full">
                Tracking
            </p>

            <h1 class="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-gray-900 leading-tight">
                Unlock The Full Power of <span class="text-indigo-600">ShipX</span> Logistics
            </h1>

            <p class="text-lg text-gray-600 max-w-lg mx-auto lg:mx-0">
                Track shipments, monitor vehicles, and analyze data—all from one smart dashboard. Ship X simplifies your logistics with full control and visibility
            </p>

            <div class="flex flex-col sm:flex-row gap-4 pt-4 justify-center lg:justify-start">
                <a href="#" class="inline-flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-full shadow-lg text-white bg-indigo-700 hover:bg-indigo-800 transition duration-300">
                    Contact us 
                    <span class="ml-2 text-xl">→</span>
                </a>
                <a href="#" class="inline-flex items-center justify-center px-8 py-3 text-base font-medium rounded-full text-indigo-700 hover:text-indigo-900 transition duration-300">
                    Get Started 
                    <span class="ml-2 text-xl">→</span>
                </a>
            </div>
        </div>

        <div class="lg:w-1/2 w-full flex justify-center lg:justify-end relative">
            
            <div class="relative w-full max-w-sm md:max-w-md h-96 lg:h-[550px] overflow-hidden rounded-2xl shadow-2xl">
                {{-- तुमच्या डिझाइनमधली इमेज इथे वापरा --}}
                <img src="{{ asset('images/Card2.png') }}" alt="Logistics Dashboard Mockup" class="w-full h-full object-cover">
                
               
                </div>
            </div>
        </div>
    </div>
</section>
<section class="bg-[#1a1a2e] py-16 md:py-24 text-white">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col lg:flex-row items-center gap-12 lg:gap-16">

        {{-- Left Content: Title, Description, CTA Buttons --}}
        <div class="lg:w-5/12 w-full space-y-6 text-center lg:text-left">
            
            <p class="text-sm font-semibold text-gray-400 uppercase tracking-widest bg-[#2c2c47] inline-block px-3 py-1 rounded-full">
                Testimonial
            </p>

            <h2 class="text-4xl sm:text-5xl lg:text-6xl font-extrabold leading-tight text-white">
                What Do Our Clients Say
            </h2>

            <p class="text-lg text-gray-300 max-w-lg mx-auto lg:mx-0">
                We make shipping simple with fast booking, real-time tracking, and secure, on-time delivery for every cargo across the globe
            </p>

            <div class="flex flex-col sm:flex-row gap-4 pt-4 justify-center lg:justify-start">
                <a href="#" class="inline-flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-full shadow-lg text-white bg-indigo-700 hover:bg-indigo-800 transition duration-300">
                    Contact us 
                    <span class="ml-2 text-xl">→</span>
                </a>
                <a href="#" class="inline-flex items-center justify-center px-8 py-3 text-base font-medium rounded-full text-indigo-400 border border-indigo-400 hover:bg-indigo-700 hover:text-white transition duration-300">
                    Get Started 
                    <span class="ml-2 text-xl">→</span>
                </a>
            </div>
        </div>

        {{-- Right Content: Testimonial Cards --}}
        <div class="lg:w-7/12 w-full grid md:grid-cols-2 gap-8 relative mt-10 lg:mt-0">
            
            {{-- Testimonial Card 1 (Olivia Jonathan) --}}
<div class="bg-[#2c2c47] p-6 sm:p-8 rounded-xl shadow-lg border border-[#3a3a5a] relative overflow-hidden">
    
    <div class="absolute inset-0 opacity-10 text-white/5">
        <svg class="h-full w-full" fill="currentColor" viewBox="0 0 100 100" preserveAspectRatio="none">
            <rect width="20" height="20" x="0" y="0"></rect>
            <rect width="20" height="20" x="40" y="0"></rect>
            <rect width="20" height="20" x="80" y="0"></rect>
            <rect width="20" height="20" x="20" y="20"></rect>
            <rect width="20" height="20" x="60" y="20"></rect>
            <rect width="20" height="20" x="0" y="40"></rect>
            <rect width="20" height="20" x="40" y="40"></rect>
            <rect width="20" height="20" x="80" y="40"></rect>
            <rect width="20" height="20" x="20" y="60"></rect>
            <rect width="20" height="20" x="60" y="60"></rect>
            <rect width="20" height="20" x="0" y="80"></rect>
            <rect width="20" height="20" x="40" y="80"></rect>
            <rect width="20" height="20" x="80" y="80"></rect>
        </svg>
    </div>
    
    <div class="relative z-10">
        
        <div class="flex items-center mb-4">
            <img src="{{ asset('images/j.jpg') }}" alt="Olivia Jonathan" class="w-12 h-12 rounded-full mr-4 object-cover">
            <div>
                <p class="font-semibold text-white">Olivia Jonathan</p>
                <p class="text-sm text-gray-400">CEO at Shipzo</p>
            </div>
        </div>
        
        <div class="mb-4 flex">
            <span class="text-blue-400">★★★★★</span>
        </div>
        
        <p class="text-gray-200 mb-6 text-lg italic leading-relaxed">
            "Ship X has completely changed the way we manage logistics. The platform is easy to use, and their tracking system keeps us updated at every step"
        </p>

        <div class="flex items-center justify-between text-sm text-gray-400">
            
            <div class="flex items-center">
                <svg class="w-4 h-4 mr-1 text-green-500" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg>
                Verified
            </div>
            
            <div class="flex items-center space-x-2">
                <span><svg class="w-4 h-4 inline-block mr-1 text-indigo-400" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd"></path></svg>Mumbai</span>
                <span class="text-indigo-400">→</span>
                <span><svg class="w-4 h-4 inline-block mr-1 text-indigo-400" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd"></path></svg>Delhi</span>
            </div>
        </div>
    </div>
</div>
            {{-- Testimonial Card 2 (You can copy/paste and modify for more cards) --}}
            <div class="bg-[#2c2c47] p-6 sm:p-8 rounded-xl shadow-lg border border-[#3a3a5a] relative overflow-hidden mt-8 md:mt-16">
                 {{-- Background pattern --}}
                 <div class="absolute inset-0 opacity-10">
                    <svg class="h-full w-full" fill="none" viewBox="0 0 100 100">
                        <path d="M0 0h20v20H0zM20 0h20v20H20zM40 0h20v20H40zM60 0h20v20H60zM80 0h20v20H80z" fill="currentColor"></path>
                        <path d="M0 20h20v20H0zM20 20h20v20H20zM40 20h20v20H40zM60 20h20v20H60zM80 20h20v20H80z" fill="currentColor"></path>
                        <path d="M0 40h20v20H0zM20 40h20v20H20zM40 40h20v20H40zM60 40h20v20H60zM80 40h20v20H80z" fill="currentColor"></path>
                        <path d="M0 60h20v20H0zM20 60h20v20H20zM40 60h20v20H40zM60 60h20v20H60zM80 60h20v20H80z" fill="currentColor"></path>
                        <path d="M0 80h20v20H0zM20 80h20v20H20zM40 80h20v20H40zM60 80h20v20H60zM80 80h20v20H80z" fill="currentColor"></path>
                    </svg>
                </div>

                <div class="relative z-10 flex items-center mb-4">
                    <img src="{{ asset('images/j.jpg') }}" alt="Marie Jane" class="w-12 h-12 rounded-full mr-4 object-cover">
                    <div>
                        <p class="font-semibold text-white">Marie Jane</p>
                        <p class="text-sm text-gray-400">CFO at Movix</p>
                    </div>
                </div>
                
                <div class="relative z-10 mb-4 flex">
                    <span class="text-blue-400">★★★★★</span>
                </div>
                
                <p class="relative z-10 text-gray-200 mb-6 text-lg italic leading-relaxed">
                    "Ship X has completely changed the way we manage logistics. The platform is easy to use, and their tracking system keeps us updated at every step"
                </p>

                <div class="relative z-10 flex items-center justify-between text-sm text-gray-400">
                    <div class="flex items-center">
                        <svg class="w-4 h-4 mr-1 text-green-500" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg>
                        Verified
                    </div>
                    <div class="flex items-center space-x-2">
                         <span><svg class="w-4 h-4 inline-block mr-1" fill="currentColor" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.538 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.783.57-1.838-.197-1.538-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.92 8.525c-.783-.57-.381-1.81.588-1.81h3.462a1 1 0 00.95-.69l1.07-3.292z"></path></svg>Mumbai</span>
                        <span>→</span>
                        <span><svg class="w-4 h-4 inline-block mr-1" fill="currentColor" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.538 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.783.57-1.838-.197-1.538-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.92 8.525c-.783-.57-.381-1.81.588-1.81h3.462a1 1 0 00.95-.69l1.07-3.292z"></path></svg>Delhi</span>
                    </div>
                </div>
            </div>

            {{-- Slider indicator (optional, if you plan to make it a carousel) --}}
            <div class="absolute -bottom-10 left-1/2 transform -translate-x-1/2 flex space-x-2">
                <div class="w-8 h-1 bg-white rounded-full"></div>
                <div class="w-2 h-1 bg-gray-600 rounded-full"></div>
                <div class="w-2 h-1 bg-gray-600 rounded-full"></div>
            </div>

        </div>
    </div>
</section>
<section class="bg-[#f8f9fa] py-16 md:py-24">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">

        <div class="mb-12">
            <p class="text-sm font-semibold text-gray-500 uppercase tracking-widest bg-gray-200 inline-block px-3 py-1 rounded-full mb-3">
                Seamless Synergy
            </p>
            <h2 class="text-4xl sm:text-5xl font-extrabold text-[#1a1a2e] mb-4">
                Partners & Integration
            </h2>
            <p class="text-lg text-gray-600 max-w-3xl mx-auto">
                We collaborate with top platforms and services to enhance functionality, ensure seamless operations, and deliver unmatched user experiences.
            </p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mt-12">
            
            {{-- Card 1: Shopify --}}
            <div class="bg-white p-6 rounded-2xl shadow-xl border border-gray-100 text-left transition duration-300 hover:shadow-2xl hover:border-indigo-100">
                <div class="flex justify-between items-center mb-4">
                    {{-- Shopify Icon (Use a local image or Tailwind class) --}}
                    <div class="w-12 h-12 bg-white rounded-lg flex items-center justify-center p-2 shadow-sm">
                        {{-- Replace with actual path to Shopify icon --}}
                        <img src="{{ asset('images/shopify.png') }}" alt="Shopify Icon" class="w-full h-full object-contain">
                    </div>
                    <span class="px-3 py-1 text-sm font-medium text-white bg-indigo-600 rounded-full">Partners</span>
                </div>
                
                <h3 class="text-xl font-semibold text-[#1a1a2e] mb-2">Shopify</h3>
                <p class="text-gray-600 mb-6 text-sm">
                    Connect your Shopify store with ShipX to streamline sales and inventory management in real time
                </p>
                <a href="#" class="inline-flex items-center text-indigo-600 font-medium text-sm px-4 py-2 rounded-full bg-indigo-50 hover:bg-indigo-100 transition duration-150">
                    Connect now
                </a>
            </div>

            {{-- Card 2: Hubspot --}}
            <div class="bg-white p-6 rounded-2xl shadow-xl border border-gray-100 text-left transition duration-300 hover:shadow-2xl hover:border-indigo-100">
                <div class="flex justify-between items-center mb-4">
                    {{-- Hubspot Icon --}}
                    <div class="w-12 h-12 bg-white rounded-lg flex items-center justify-center p-2 shadow-sm">
                        <img src="{{ asset('images/Mailchimp.png') }}" alt="Hubspot Icon" class="w-full h-full object-contain">
                    </div>
                    <span class="px-3 py-1 text-sm font-medium text-white bg-indigo-600 rounded-full">Partners</span>
                </div>
                
                <h3 class="text-xl font-semibold text-[#1a1a2e] mb-2">Hubspot</h3>
                <p class="text-gray-600 mb-6 text-sm">
                    Connect HubSpot with ShipX to align sales, marketing, and inventory insights for better decision-making
                </p>
                <a href="#" class="inline-flex items-center text-indigo-600 font-medium text-sm px-4 py-2 rounded-full bg-indigo-50 hover:bg-indigo-100 transition duration-150">
                    Connect now
                </a>
            </div>

            {{-- Card 3: Mailchimp --}}
            <div class="bg-white p-6 rounded-2xl shadow-xl border border-gray-100 text-left transition duration-300 hover:shadow-2xl hover:border-indigo-100">
                <div class="flex justify-between items-center mb-4">
                    {{-- Mailchimp Icon --}}
                    <div class="w-12 h-12 bg-white rounded-lg flex items-center justify-center p-2 shadow-sm">
                        <img src="{{ asset('images/hubspot.png') }}" alt="Mailchimp Icon" class="w-full h-full object-contain">
                    </div>
                    <span class="px-3 py-1 text-sm font-medium text-white bg-indigo-600 rounded-full">Partners</span>
                </div>
                
                <h3 class="text-xl font-semibold text-[#1a1a2e] mb-2">Mailchimp</h3>
                <p class="text-gray-600 mb-6 text-sm">
                    Sync your warehouse data with Mailchimp to automate order updates, customer engagement, and campaigns
                </p>
                <a href="#" class="inline-flex items-center text-indigo-600 font-medium text-sm px-4 py-2 rounded-full bg-indigo-50 hover:bg-indigo-100 transition duration-150">
                    Connect now
                </a>
            </div>

        </div>

        <div class="mt-16">
            <a href="#" class="inline-flex items-center justify-center px-8 py-3 text-base font-medium rounded-full shadow-lg text-white bg-indigo-600 hover:bg-indigo-700 transition duration-300">
                See all 
                <span class="ml-2 text-xl">→</span>
            </a>
        </div>
    </div>
</section>
<section class="bg-[#e9effd] py-16 md:py-24">
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">

        <div class="mb-12">
            <span class="text-sm font-semibold text-gray-700 uppercase tracking-widest bg-white inline-block px-3 py-1 rounded-full border border-gray-300 shadow-sm">
                FAQ
            </span>
            <h2 class="text-5xl font-extrabold text-[#1a1a2e] mt-4 mb-3">
                Frequently Asked Question
            </h2>
            <p class="text-lg text-gray-600 max-w-2xl mx-auto">
                Everything you need to know about using Ship X, from shipment tracking to client management
            </p>
        </div>

        <div class="space-y-4 text-left">
            
            {{-- FAQ Item 1 (Open by Default) --}}
            <div class="faq-item bg-white p-6 rounded-2xl shadow-lg border border-gray-100">
                <button class="faq-question w-full flex justify-between items-center text-lg font-semibold text-[#1a1a2e]" 
                        onclick="toggleAccordion(1)">
                    How do I track my shipment?
                    {{-- Minus Icon for Open State --}}
                    <span id="icon-1" class="text-3xl text-gray-500 transition duration-300">−</span>
                </button>
                <div id="answer-1" class="faq-answer mt-4 pt-4 border-t border-gray-100 text-gray-600" style="display: block;">
                    Everything you need to know about using Ship X, from shipment tracking to client management. Find quick answers to common queries below.
                </div>
            </div>

            {{-- FAQ Item 2 --}}
            <div class="faq-item bg-white p-6 rounded-2xl shadow-lg border border-gray-100">
                <button class="faq-question w-full flex justify-between items-center text-lg font-semibold text-[#1a1a2e]" 
                        onclick="toggleAccordion(2)">
                    Can I manage multiple shipments at once?
                    {{-- Plus Icon for Closed State --}}
                    <span id="icon-2" class="text-3xl text-gray-500 transition duration-300">+</span>
                </button>
                <div id="answer-2" class="faq-answer hidden mt-4 pt-4 border-t border-gray-100 text-gray-600">
                    Yes, Ship X provides a centralized dashboard allowing you to view, track, and manage all your ongoing and completed shipments simultaneously, saving you time and effort.
                </div>
            </div>

            {{-- FAQ Item 3 --}}
            <div class="faq-item bg-white p-6 rounded-2xl shadow-lg border border-gray-100">
                <button class="faq-question w-full flex justify-between items-center text-lg font-semibold text-[#1a1a2e]" 
                        onclick="toggleAccordion(3)">
                    Is there a mobile app for Ship X?
                    <span id="icon-3" class="text-3xl text-gray-500 transition duration-300">+</span>
                </button>
                <div id="answer-3" class="faq-answer hidden mt-4 pt-4 border-t border-gray-100 text-gray-600">
                    Currently, Ship X offers a fully responsive web application accessible on all devices. A dedicated mobile app is under development and will be released soon!
                </div>
            </div>

            {{-- FAQ Item 4 --}}
            <div class="faq-item bg-white p-6 rounded-2xl shadow-lg border border-gray-100">
                <button class="faq-question w-full flex justify-between items-center text-lg font-semibold text-[#1a1a2e]" 
                        onclick="toggleAccordion(4)">
                    Can I integrate Ship X with my business system?
                    <span id="icon-4" class="text-3xl text-gray-500 transition duration-300">+</span>
                </button>
                <div id="answer-4" class="faq-answer hidden mt-4 pt-4 border-t border-gray-100 text-gray-600">
                    Absolutely. Ship X offers robust API access and direct integrations with popular platforms like Shopify, HubSpot, and Mailchimp, ensuring seamless data synchronization.
                </div>
            </div>

        </div>

        <div class="mt-16">
            <a href="#" class="inline-flex items-center justify-center px-10 py-3 text-base font-medium rounded-full shadow-lg text-white bg-indigo-600 hover:bg-indigo-700 transition duration-300">
                Ask a question
            </a>
        </div>
    </div>
</section>
<section class="bg-[#1a1a2e] py-16 md:py-24">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

        <div class="flex flex-col lg:flex-row rounded-3xl overflow-hidden shadow-2xl bg-[#1a1a2e] min-h-[600px]">

            <div class="lg:w-1/2 w-full min-h-[300px] lg:min-h-full">
                {{-- नकाश्यासाठी प्लेसहोल्डर. तुम्ही येथे Google Maps API किंवा iframe वापरू शकता. --}}
                <div class="w-full h-full">
                    {{-- Google Maps Embed साठी iframe चा वापर करा. येथे फक्त प्लेसहोल्डर इमेज आहे. --}}
                    {{--  --}}
                    <img src="{{ asset('images/map.png') }}" alt="Global Map with Location Pin" 
                         class="w-full h-full object-cover">
                </div>
            </div>

            <div class="lg:w-1/2 w-full p-8 md:p-12 text-white">
                <h2 class="text-3xl md:text-4xl font-extrabold mb-8">Send Us A Message</h2>

             <form action="{{ route('lead.store') }}" method="POST" enctype="multipart/form-data" class="space-y-6">
    @csrf

    {{-- Row 1: Full Name and Business Name --}}
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <input type="text" name="name" placeholder="Full Name" required 
               class="w-full px-4 py-3 rounded-lg bg-transparent border border-[#3a3a5a] text-white focus:ring-indigo-500 focus:border-indigo-500 placeholder-gray-500" />

        <input type="text" name="business_name" placeholder="Business Name"
               class="w-full px-4 py-3 rounded-lg bg-transparent border border-[#3a3a5a] text-white focus:ring-indigo-500 focus:border-indigo-500 placeholder-gray-500" />
    </div>

    {{-- Row 2: Email ID and Phone Number --}}
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <input type="email" name="email" placeholder="Email Id" required 
               class="w-full px-4 py-3 rounded-lg bg-transparent border border-[#3a3a5a] text-white focus:ring-indigo-500 focus:border-indigo-500 placeholder-gray-500" />

        <input type="tel" name="phone" placeholder="Phone Number"
               class="w-full px-4 py-3 rounded-lg bg-transparent border border-[#3a3a5a] text-white focus:ring-indigo-500 focus:border-indigo-500 placeholder-gray-500" />
    </div>

    {{-- Row 3: Choose File --}}
    <div class="relative">
        <label for="file_upload" class="flex justify-between items-center w-full px-4 py-3 rounded-lg bg-transparent border border-[#3a3a5a] cursor-pointer hover:border-indigo-500 transition duration-150">
            <span class="text-gray-500" id="file_name_display">Choose File</span>
            <span class="text-white font-medium px-3 py-1 bg-[#3a3a5a] rounded-md">No File Chosen</span>
        </label>
        <input type="file" id="file_upload" name="attachment" class="absolute inset-0 opacity-0 w-full h-full cursor-pointer"
               onchange="document.getElementById('file_name_display').textContent = this.files[0] ? this.files[0].name : 'Choose File'" />
    </div>

    {{-- Row 4: Your Message --}}
    <div>
        <textarea name="message" placeholder="Your Message" rows="5" required 
                  class="w-full px-4 py-3 rounded-lg bg-transparent border border-[#3a3a5a] text-white focus:ring-indigo-500 focus:border-indigo-500 placeholder-gray-500 resize-none"></textarea>
    </div>

    {{-- Submit Button --}}
    <div>
        <button type="submit" class="w-full md:w-auto inline-flex items-center justify-center px-8 py-3 text-base font-medium rounded-lg shadow-lg text-white bg-green-600 hover:bg-green-700 transition duration-300">
            Submit
        </button>
    </div>
</form>

            </div>
        </div>
    </div>
</section>

{{-- The new Footer section starts here --}}
<footer class="bg-white border-t border-gray-200 pt-16 pb-10 text-gray-700">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {{-- Top part: Logo, Socials, Copyright --}}
        <div class="flex flex-col md:flex-row justify-between items-start md:items-center border-b border-gray-200 pb-10 mb-10">
            
            {{-- Logo and Socials Group --}}
            <div class="flex flex-col md:flex-row md:items-center space-y-6 md:space-y-0 md:space-x-12 w-full md:w-auto">
                <div class="flex items-center space-x-2">
                    {{-- ShipX Logo (Placeholder for the provided image logo) --}}
                    <div class="w-8 h-8 flex items-center justify-center text-indigo-600">
                        {{-- ShipX Icon SVG Placeholder --}}
                        <svg class="w-full h-full" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M12 2L2 7V17L12 22L22 17V7L12 2Z" fill="currentColor" fill-opacity="0.8"/>
                            <path d="M12 4L4 8L12 12L20 8L12 4Z" fill="currentColor" fill-opacity="0.6"/>
                            <path d="M12 14L4 17V19L12 22L20 19V17L12 14Z" fill="currentColor" fill-opacity="0.4"/>
                        </svg>
                    </div>
                    <span class="text-xl font-bold text-gray-900">ShipX</span>
                </div>
                
                {{-- Social Media Icons --}}
                <div class="flex space-x-4">
                    <a href="#" class="w-8 h-8 flex items-center justify-center border border-gray-300 rounded-full text-gray-500 hover:text-indigo-600 transition duration-150">
                        {{-- Twitter/X Icon --}}
                        <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24"><path d="M18.901 1.996h3.189l-8.084 9.172 9.421 11.832h-7.619l-6.19-7.797-7.749 7.797H.99l8.47-8.914L0 1.996h8.04L13.25 8.783 18.9 1.996zm-2.094 18.06h2.24l-7.05-8.006-7.85-8.006h-2.31l8.52 9.006 7.69 7.006z"/></svg>
                    </a>
                    <a href="#" class="w-8 h-8 flex items-center justify-center border border-gray-300 rounded-full text-gray-500 hover:text-indigo-600 transition duration-150">
                        {{-- Facebook/Placeholder Icon (using a circle as per the image's generic circle style) --}}
                        <div class="w-2 h-2 bg-gray-500 rounded-full"></div> 
                    </a>
                    <a href="#" class="w-8 h-8 flex items-center justify-center border border-gray-300 rounded-full text-gray-500 hover:text-indigo-600 transition duration-150">
                        {{-- LinkedIn Icon --}}
                        <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24"><path d="M22.23 0H1.77C.79 0 0 .77 0 1.77v20.46C0 23.23.77 24 1.77 24h20.46c.98 0 1.77-.77 1.77-1.77V1.77C24 .77 23.23 0 22.23 0zM7.27 20.37H3.64V9H7.27v11.37zm-1.81-13.06c-1.16 0-2.11-.95-2.11-2.11S4.3 3.09 5.46 3.09s2.11.95 2.11 2.11-1 2.11-2.11 2.11zm15.86 13.06h-3.63v-5.6c0-1.34-.02-3.07-1.87-3.07-1.87 0-2.16 1.46-2.16 2.97v5.7h-3.63V9h3.49v1.6h.05c.48-.91 1.66-1.87 3.44-1.87 3.68 0 4.36 2.42 4.36 5.58v6.06z"/></svg>
                    </a>
                </div>
            </div>
            
            {{-- Copyright --}}
            <p class="text-sm text-gray-500 mt-6 md:mt-0 md:ml-auto">
                &copy;2025 ShipX. All Rights Reserved.
            </p>
        </div>

        {{-- Bottom part: Subscribe and Nav Links --}}
        <div class="grid grid-cols-1 md:grid-cols-5 lg:grid-cols-5 gap-10">
            
            {{-- Column 1: Subscribe --}}
            <div class="md:col-span-2 lg:col-span-2">
                <h4 class="text-base font-semibold text-gray-900 mb-4">Subscribe to Chainex</h4>
                <div class="flex">
                    <input 
                        type="email" 
                        placeholder="Enter your Email"
                        class="px-4 py-2 border border-gray-300 rounded-l-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 w-full md:max-w-xs text-sm"
                    >
                    <button 
                        type="submit"
                        class="px-6 py-2 bg-indigo-600 text-white font-medium rounded-r-lg hover:bg-indigo-700 transition duration-150 text-sm"
                    >
                        Sign up
                    </button>
                </div>
            </div>

            {{-- Column 2: Explore --}}
            <div>
                <h4 class="text-base font-semibold text-gray-900 mb-4">Explore</h4>
                <ul class="space-y-2 text-sm">
                    <li><a href="#" class="hover:text-indigo-600 transition duration-150">Home</a></li>
                    <li><a href="#" class="hover:text-indigo-600 transition duration-150">About Us</a></li>
                    <li><a href="#" class="hover:text-indigo-600 transition duration-150">Solutions</a></li>
                    <li><a href="#" class="hover:text-indigo-600 transition duration-150">Blog</a></li>
                </ul>
            </div>

            {{-- Column 3: Solutions --}}
            <div>
                <h4 class="text-base font-semibold text-gray-900 mb-4">Solutions</h4>
                <ul class="space-y-2 text-sm">
                    <li><a href="#" class="hover:text-indigo-600 transition duration-150">Freight Management</a></li>
                    <li><a href="#" class="hover:text-indigo-600 transition duration-150">Order Tracking</a></li>
                    <li><a href="#" class="hover:text-indigo-600 transition duration-150">Carrier Integration</a></li>
                    <li><a href="#" class="hover:text-indigo-600 transition duration-150">Analytics Dashboard</a></li>
                </ul>
            </div>

            {{-- Column 4: Resources --}}
            <div>
                <h4 class="text-base font-semibold text-gray-900 mb-4">Resources</h4>
                <ul class="space-y-2 text-sm">
                    <li><a href="#" class="hover:text-indigo-600 transition duration-150">Help Center</a></li>
                    <li><a href="#" class="hover:text-indigo-600 transition duration-150">FAQs</a></li>
                    <li><a href="#" class="hover:text-indigo-600 transition duration-150">Terms of Service</a></li>
                    <li><a href="#" class="hover:text-indigo-600 transition duration-150">Privacy Policy</a></li>
                </ul>
            </div>

        </div>
    </div>
</footer>

@endsection